### ISSUE TITLE
试了下，渲染出两张图出来 

### ISSUE THREAD

**Issue by egolearner** [zuisong/notion-kroki#2]
![image](https://github.com/zuisong/notion-kroki/assets/45122959/dbb1a57d-cccd-4730-87a5-41547fe53d61)
浏览器为Edge，在隐身模式下只开启油猴插件也是一样，应该可以排除其他插件的影响。
麻烦看下是什么问题

**Comment by zuisong** [comment]
测试了一下  确实存在这个问题  稍后发版修复

**Comment by zuisong** [comment]
❤️ 感谢反馈
1.3.0 版本已经修复了   油桃猴获取新版本应该会自动更新 😄
